name: Create and Publish Module Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Update Version
      shell: bash
      id: set-version
      run: echo "::set-output name=version::$(node ./.github/workflows/set-version.js ${{ github.ref }})"
    - run: zip -r ./awakening.zip module.json custom_config.js
    - name: Create Release
      id: create_versioned_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Release ${{ steps.set-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./awakening.zip'