name: Create and Publish Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'awakening.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: actions/checkout@v2
      uses: ncipollo/release-action@v1
      with:
        artifacts: "awakening.zip"
        token: ${{ secrets.GITHUB_TOKEN }}